# ItemBanPlus 1.2.0
# Pixelmon 포함 모드 아이템 금지를 'ID' 또는 '이름' 패턴으로 설정합니다.
# - id: 는 Forge 레지스트리 이름(예: pixelmon:mystery_box, pixelmon:.*_mint) 정규식입니다.
# - name: 은 표시이름(색코드 제거, 소문자) 정규식입니다.
# - material: 은 Bukkit Material 이름(예: DIAMOND_SWORD). (Pixelmon에는 권장하지 않음)
version: 1.2.0

messages:
  denied: "&c해당 아이템은 사용이 금지되었습니다. (이유: %reason%)"

bans:
  right-click:
    - "id:pixelmon:mystery_box"
    - "id:pixelmon:.*_mint"
  craft:
    - "id:pixelmon:mystery_box"
    - "id:pixelmon:.*_mint"
  pixelmon-interact:
    - "id:pixelmon:mystery_box"
    - "id:pixelmon:.*_mint"

options:
  # Pixelmon GUI(예: 파티/보관함 등)의 제목이나 홀더 클래스명에 'pixelmon'이 포함되면 클릭을 막습니다.
  detect-pixelmon-inventory-by-title: true
