name: ItemBanPlus
main: gg.minpack.itemban.ItemBanPlusPlugin
version: 1.0.0
api-version: 1.16
author: minpack
commands:
  아이템금지:
    description: 금지 아이템 GUI를 엽니다.
    permission: minpack.itemban
    aliases: [itemban]
permissions:
  minpack.itemban:
    default: op
