name: ItemBanPlus
main: gg.minpack.itemban.ItemBanPlusPlugin
version: 1.2.2
api-version: 1.16
author: minpack
commands:
  아이템금지:
    description: 금지 아이템 GUI 없이 설정파일 기반 금지 기능 (이 버전은 설정파일 매칭 위주).
    permission: minpack.itemban
    aliases: [itemban]
permissions:
  minpack.itemban:
    default: op
